# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMTemplateServiceConnection'
    subscriptionId: '5ba73d84-ad8e-442c-bf7c-f4642263a3e1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'vimallabs'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/PistolPete17/ARMTemplate/main/azuredeploy2.json'
    overrideParameters: '-projectName ARMTestEnvironment'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployARMTemplate'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
