# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMTemplateServiceConnection'
    subscriptionId: '5ba73d84-ad8e-442c-bf7c-f4642263a3e1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'vimallabs'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/PistolPete17/ARMTemplate/main/azure-pipelines-2.yml'
    csmParametersFileLink: 'https://raw.githubusercontent.com/PistolPete17/ARMTemplate/main/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'Ron Test Environment'
